image: gitpod/workspace-base

tasks:
  - before: |
      source scripts/setup.sh
    init: |
      deno task cache

ports:
  - name: Flagopolis
    port: 8000
    onOpen: notify

vscode:
  extensions:
    - denoland.vscode-deno
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    # - sastan.twind-intellisense

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true

checkoutLocation: flagopolis
workspaceLocation: flagopolis/flagopolis.code-workspace
