image: gitpod/workspace-base

tasks:
  - before: |
      source scripts/setup.sh
    init: |
      deno cache --config flagopolis/deno.json --lock flagopolis/lock.json flagopolis/dev.ts flagopolis/main.ts
    command: |
      cd flagopolis
      deno task start

ports:
  - name: Flagopolis
    port: 8000
    onOpen: notify

vscode:
  extensions:
    - denoland.vscode-deno
    - eamodio.gitlens
    # - sastan.twind-intellisense

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true

checkoutLocation: flagopolis
workspaceLocation: flagopolis/flagopolis.code-workspace
